

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/youtube2?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: zxcv1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug